src/SonOfCod/Controllers/MarketingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SonOfCod.Controllers
{
    public class MarketingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SonOfCod/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using SonOfCod.Models;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace SonOfCod.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RolesController : Controller
    {
        private readonly SonOfCodDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public RolesController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, SonOfCodDbContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.Roles.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IdentityRole role)
        {
            role.NormalizedName = role.Name.ToUpper();
            _db.Roles.Add(role);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(string roleName)
        {
            IdentityRole role = _db.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            return View(role);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(IdentityRole role)
        {
            role.NormalizedName = role.Name.ToUpper();
            _db.Entry(role).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string roleName)
        {
            IdentityRole role = _db.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            _db.Roles.Remove(role);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult ManageUserRoles()
        {
            List<SelectListItem> list = _db.Roles.OrderBy(r => r.Name)
                .ToList()
                .Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name })
                .ToList();
            ViewBag.Roles = list;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRoleToUser(string userName, string roleName)
        {
            ApplicationUser user = _db.Users.Where(u => u.UserName.Equals(userName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            await _userManager.AddToRoleAsync(user, roleName);
            return RedirectToAction("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ApplicationUser user = _db.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                ViewBag.RolesForThisUser = await _userManager.GetRolesAsync(user);
            }
            List<SelectListItem> list = _db.Roles.OrderBy(r => r.Name)
                .ToList()
                .Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name })
                .ToList();
            ViewBag.Roles = list;
            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveRoleFromUser(string userName, string roleName)
        {
            ApplicationUser user = _db.Users.Where(u => u.UserName.Equals(userName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            bool isInRole = await _userManager.IsInRoleAsync(user, roleName);
            if (isInRole)
            {
                ViewBag.ResultMessage = "Role removed from user.";
                await _userManager.RemoveFromRoleAsync(user, roleName);
            }
            else
            {
                ViewBag.ResultMessage = "User is not assigned to selected role.";
            }
            return RedirectToAction("ManageUserRoles");
        }
    }
}

src/SonOfCod/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
    <script type="text/javascript" src="~/js/scripts.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/styles.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="blue lighten-2">
        <div class="nav-wrapper">
            <ul class="left">
                <li>@Html.ActionLink("About Son of Cod", "Index", "Marketing")</li>
                <li>@Html.ActionLink("Newsletter", "Index", "Newsletter")</li>
            </ul>
            <span class="brand-logo center">@Html.ActionLink("Son of Cod", "Index", "Home")</span>
            <ul class="right">
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink($"{User.Identity.Name}'s Account", "Index", "Account", null, new { @class = "grey-text text-lighten-3" })</li>
                    <li>@Html.ActionLink("User Roles", "Index", "Roles", null, new { @class = "grey-text text-lighten-3" })</li>
                }
                else
                {
                    <li>@Html.ActionLink("Login", "Index", "Account")</li>
                }

            </ul>
        </div>
    </nav>

    <div class="parallax-container">
        <div class="parallax"><img src="~/images/banner.jpg"></div>
    </div>

    <main class="container">
        @RenderBody()
    </main>

    <footer class="page-footer blue lighten-2">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Son of Cod</h5>
                </div>
                <div class="col l4 offset-l2 s12 hide-on-med-and-down">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li>@Html.ActionLink("Newsletter", "Index", "Newsletter", null, new { @class = "grey-text text-lighten-3 footer-links" })</li>
                        <li>@Html.ActionLink("About Son of Cod", "Index", "Marketing", null, new { @class = "grey-text text-lighten-3 footer-links" })</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Account Settings", "Index", "Account", null, new { @class = "grey-text text-lighten-3 footer-links" })</li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2017 Copyright Levi Bibo
                <a class="grey-text text-lighten-4 right" href="https://www.github.com/levibibo/sonofcod">GitHub</a>
            </div>
        </div>
    </footer>
</body>
</html>