src/SonOfCod/Controllers/NewsletterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using SonOfCod.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace SonOfCod.Controllers
{
    public class NewsletterController : Controller
    {
        private SonOfCodDbContext db = new SonOfCodDbContext();

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost, ActionName("Signup")]
        public IActionResult SignupUser()
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            NewsletterRecipient newRecipient = new NewsletterRecipient() { };
            newRecipient.AppUserId = userId;
            db.MailingList.Add(newRecipient);
            db.SaveChanges();
            return RedirectToAction("AddedToNewsletter");
        }

        public IActionResult AddedToNewsletter()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult MailingList()
        {
            List<ApplicationUser> mailingList = db.MailingList.Include(ml => ml.AppUser)
                .ToList()
                .Select(ml => ml.AppUser)
                .ToList();
            return View(mailingList);
        }
    }
}

src/SonOfCod/Views/Newsletter/AddedToNewsletter.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Security.Claims

<h1>Added to Newsletter</h1>
<hr />
<h2>Thank you!</h2>
<p>You will now receive our regular newsletter.</p>

src/SonOfCod/Views/Newsletter/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Security.Claims

<h1>Newsletter</h1>
<hr />
<h2>About our newsletter:</h2>
<p>Tempor dolore ipsum ut feugait dolore sed amet labore lorem exerci dolor accusam sanctus nulla est diam sit commodo lorem tempor sea dolor stet stet hendrerit in labore sadipscing magna gubergren sanctus tempor ipsum elitr est dolor lorem et enim ipsum sit justo dolores sit et ut sit gubergren kasd et rebum elitr aliquyam lobortis erat in nonumy dolor et elitr sadipscing sea dolor diam magna magna sit autem nisl vero consectetuer consequat tempor dolor laoreet nonumy voluptua luptatum feugiat sea tempor vero aliquip sed amet accusam sanctus magna rebum amet takimata sit est dolore consetetur et consectetuer eum illum</p>
<p>@Html.ActionLink("Sign up!", "Signup", "Newsletter")</p>

src/SonOfCod/Views/Newsletter/MailingList.cshtml
@{
    ViewData["Title"] = "Newsletter Mailing List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using SonOfCod.Models
@model List<ApplicationUser>

<h1>Mailing List</h1>
<hr />
<ul>
    @foreach (ApplicationUser user in Model)
    {
        <li><strong>Name:</strong> @user.UserName - <strong>Email Address:</strong> <a href="mailto:@user.Email">@user.Email</a></li>
    }
</ul>

src/SonOfCod/Views/Newsletter/Signup.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Security.Claims

<h1>Newsletter Signup</h1>
<hr />
<h2>Would you like to sign up for our newsletter?</h2>
<div class="row">
    <div class="col s12 m6 center">
        @using (Html.BeginForm("Signup", "Newsletter", FormMethod.Post))
        {
            <button class="btn green" type="submit">Yes Please</button>
        }
    </div>
    <div class="col s12 m6 center">
        @Html.ActionLink("Never Mind", "Index", "Newsletter", null, new { @class = "btn red" })
    </div>
</div>